### ISSUE TITLE
100% did something dumb 

### ISSUE THREAD

**Issue by ForT4eHorde** [Magisk-Modules-Alt-Repo/microG-GApps#10]
I installed the module, most of the apps started to crash, uninstalled the module 
The issue is still there
But now there's less crashes and I can actually open smth
like gp, however it shut downs after about 5sec

Is there a way to restore everything as it was? 

After some poking around and deleting gp services apps don't crash, they just don't work properly
Note: I think most non Google apps work fine now, even chrome, but I can't sign in into Google account 

I have no idea how to revert it and I pray it's just possible

**Comment by goon-123** [comment]
Same thing happened to me.... How did you fix it?

**Comment by goon-123** [comment]
Fixed it by booting into recovery -> factory reset
Log into google services and setting up account works
Reinstall Magisk app and launched it
Prompted me to reboot to finish rooting 
Everything OK
