### ISSUE TITLE
Module to install Play Store only?

### ISSUE THREAD

**Issue by bege10** [Magisk-Modules-Alt-Repo/microG-GApps#11]
Hello,
I had used LineageOS for microG and now /e/OS with the Play Store from NanoDroid for years, eventually it didn't scan for installed apps. After reinstalling the module it additionally did not recognize paid apps any more.  I was lucky. Restoring the backed up app data at least made it recognize the paid apps again.

Some time ago I merged your newer Play Store (APK, lib and prefs) to the NanoDroid module and it continue to work as described. Same with the module Fakestore2playstore.

Now I had to wipe data in order to get a system upgrade from Android 10 to 11 and now restoring the app data does not help. The app neither scans for the installed apps nor recognizes the paid apps. When opening the screens for apps (updates and managing) It shows that an error has occurred and I should try again. Always the same.
Users of fakestore2playstore have the same issue with paid apps:
https://github.com/sn-00-x/fakestore2playstore/issues/1

So currently I don't find a way to get my paid apps installed. Restoring backed up app that come with a key APK do work, but those that need verification from the Play Store, and that is the majority, don't

Does the Play Store work correct with your module if it is installed as a whole to a system that does not have microG preinstalled?
If so, could you provide a module to only install the Play Store to a system that has microG preinstalled? That would be a great help.

**Comment by Psk-Ita** [comment]
unfortunately it depends not only on the playstore version
some apps need real playservices to be authorized.
anyway, to keep just the playstore, you can flash the module, locate it's folder in /data/adb/modules
keep just
/system/priv-app/vending or phonesky
/system/etc/permissions/com.android.vending.xml

locate the fakestore app in your /system partition
replicate the path in module's folder, put.".replace" file in it, it should work

**Comment by szzuuui** [comment]
my play store has stopped itself after installing this module, i tried to uninstall it but it's the same i still can't open playstore, then how to fix it?

**Comment by Psk-Ita** [comment]
If you are experiencing "ERR-01" message
just delere playstore data, ensure permissions and network access, it should work

otherwise remive the module, and try to install microG manually or following other guides, it could depends on to many variables

**Comment by szzuuui** [comment]
Now I'm using the derpfest rom that already has the Google application
installed, actually I was just installing the module for fun, but my
playstore has stopped itself, I've deleted the module but it's the same, my
playstore can't be opened

Pada tanggal Sab, 4 Feb 2023 02.59, Psk-It ***@***.***>
menulis:

**Comment by bege10** [comment]
> unfortunately it depends not only on the playstore version some apps need real playservices to be authorized. anyway, to keep just the playstore, you can flash the module, locate it's folder in /data/adb/modules keep just /system/priv-app/vending or phonesky /system/etc/permissions/com.android.vending.xml
> 
> locate the fakestore app in your /system partition replicate the path in module's folder, put.".replace" file in it, it should work

Thank you very much!
Meanwhile the Play Store works after I managed to have microG pass SafetyNet certification.
https://github.com/sn-00-x/fakestore2playstore/issues/1#issuecomment-1382905802
So you are right that it is not an issue of the Store version. But your suggestion is a way to use the newer version in your module if necessary or wanted.
Can you confirm that the Play Store now needs the phone to pass SafetyNet certification?

**Comment by Psk-Ita** [comment]
No
on all roms i tried safety net does not pass, but play storie runs propertly
Maybe your problem is about permissions (xml files in /system/etc/permissions i mean)
i don't know if it could be useful, in any case i updated them

**Comment by bege10** [comment]
> No on all roms i tried safety net does noto passato, but play storie runs propertly Maybe your problem is about permissions (xml files in /system/etc/permissions i mean) i don't know if it could be useful, in any case i updated them

Thank you for updating the module.
After flashing a fresh system (/e/OS Android 12) I installed your module.

- I installed the module, deactivated it (because microG comes already with /e/OS) and rebooted.
- Did as you recommended here https://github.com/Magisk-Modules-Alt-Repo/microG-GApps/issues/11#issuecomment-1410819941
- enabled the module and rebooted.

The Play Store is in the app drawer but not in the app list (system apps enabled) in Android settings.
It crashes right away when I try to start it from the app drawer.
This is the log provided by Scoop

> FATAL EXCEPTION: main
Process: com.android.vending, PID: 4268
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
	at android.app.ActivityThread.installProvider(ActivityThread.java:7464)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
	at android.support.v4.content.FileProvider.b(PG:26)
	at android.support.v4.content.FileProvider.attachInfo(PG:4)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7459)
	... 11 more

**Comment by Psk-Ita** [comment]
> > No on all roms i tried safety net does noto passato, but play storie runs propertly Maybe your problem is about permissions (xml files in /system/etc/permissions i mean) i don't know if it could be useful, in any case i updated them
> 
> Thank you for updating the module. After flashing a fresh system (/e/OS Android 12) I installed your module.
> 
> * I installed the module, deactivated it (because microG comes already with /e/OS) and rebooted.
> * Did as you recommended here [Module to install Play Store only? #11 (comment)](https://github.com/Magisk-Modules-Alt-Repo/microG-GApps/issues/11#issuecomment-1410819941)
> * enabled the module and rebooted.
> 
> The Play Store is in the app drawer but not in the app list (system apps enabled) in Android settings. It crashes right away when I try to start it from the app drawer. This is the log provided by Scoop
> 
> > FATAL EXCEPTION: main
> > Process: com.android.vending, PID: 4268
> > java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
> > at android.app.ActivityThread.installProvider(ActivityThread.java:7464)
> > at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
> > at android.app.ActivityThread.access$1500(ActivityThread.java:256)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loopOnce(Looper.java:201)
> > at android.os.Looper.loop(Looper.java:288)
> > at android.app.ActivityThread.main(ActivityThread.java:7870)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> > Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
> > at android.support.v4.content.FileProvider.b(PG:26)
> > at android.support.v4.content.FileProvider.attachInfo(PG:4)
> > at android.app.ActivityThread.installProvider(ActivityThread.java:7459)
> > ... 11 more

Ciao,
if you need only playstore, you can just delete all other files in the module folder, except /system/priv-app/[Phonesky or Vending]
this time i kept contact sync and calensar sync (up to you to keep or remove them - you need to manually enable grants for both in order to run sync) just ensure to keep /system/etc/permissions folder

**Comment by bege10** [comment]
> Ciao,
> if you need only playstore, you can just delete all other files in the module folder, except /system/priv-app/[Phonesky or Vending]
> this time i kept contact sync and calensar sync (up to you to keep or remove them - you need to manually enable grants for both in order to run sync) just ensure to keep /system/etc/permissions folder

Thanks!
I did as in your linked post above. In the permissions folder I only kept the permissions for vending and phonesky, because /e/OS comes with a full microG installation with sync functionality. Otherwise I think the permissions might get in conflict, and I don't need contact and calendar sync.
The module installs Phonesky, what I think is correct for Android 12, 64-bit. Nevertheless, the Play Store is not fully installed as described above. In Apps it is only listed as `com.google.android.finsky.application.classic.ClassicProdApplication` and not as `Google Play Store`. In Nova Launcher it does not appear in the app drawer at all.

"Just for fun" I exchanged it for vending. Believe it or not, it works!
Do you have an idea what is wrong with Phonesky?

**Comment by Psk-Ita** [comment]
> > Ciao,
> > if you need only playstore, you can just delete all other files in the module folder, except /system/priv-app/[Phonesky or Vending]
> > this time i kept contact sync and calensar sync (up to you to keep or remove them - you need to manually enable grants for both in order to run sync) just ensure to keep /system/etc/permissions folder
> 
> Thanks! I did as in your linked post above. In the permissions folder I only kept the permissions for vending and phonesky, because /e/OS comes with a full microG installation with sync functionality. Otherwise I think the permissions might get in conflict, and I don't need contact and calendar sync. The module installs Phonesky, what I think is correct for Android 12, 64-bit. Nevertheless, the Play Store is not fully installed as described above. In Apps it is only listed as `com.google.android.finsky.application.classic.ClassicProdApplication` and not as `Google Play Store`. In Nova Launcher it does not appear in the app drawer at all.
> 
> "Just for fun" I exchanged it for vending. Believe it or not, it works! Do you have an idea what is wrong with Phonesky?

Not sure, but I think you have to replace fakestore that is included in /e/OS
tipically it is under /system/priv-app (or other app/priv-app folder under /system partition)

**Comment by bege10** [comment]
> Not sure, but I think you have to replace fakestore that is included in /e/OS
> tipically it is under /system/priv-app (or other app/priv-app folder under /system partition)

I did that already with the not working Phonesky.
