### ISSUE TITLE
Micro G is crashing the whole time in the Background 

### ISSUE THREAD

**Issue by BotAndis** [Magisk-Modules-Alt-Repo/microG-GApps#13]
Im getting the following Error: "microG Services Core wird wiederholt beendet" translated it Just means"microG Services Core is repeatedly
closed" .

Im not sure why this ist happening, If I search the it comes up with a answer including "best sign" Banking App which I use...  But it dosen't really Help because it is just saying to Update microG.

I would appreciate any help.
![Screenshot_20230319_132240_Chrome](https://user-images.githubusercontent.com/59452948/226175036-e7a47a23-2bd7-4f7f-b7e9-47c7a0aeb8f2.jpg)

**Comment by Konstantin-DonBass** [comment]
thanks, I overdid it, I activated a lot of modules, I'm already restoring
from a backup copy.

вс, 19 мар. 2023 г., 15:27 Andis ***@***.***>:

**Comment by Psk-Ita** [comment]
that error happend to me, when microG gas not required grants assigned, so check out permissions
