### ISSUE TITLE
Sudden crashes and malfunctions

### ISSUE THREAD

**Issue by INDRAPhilip** [Magisk-Modules-Alt-Repo/microG-GApps#7]
Bugs and glitches bug in my device microG service stops on startup and the Play Store does not work any of their services just keeps restarting the device after a while.

**Comment by INDRAPhilip** [comment]
In my case I remove the module and then I run out of Play Store works asking me to download Google Play Services How could I solve it.

**Comment by Psk-Ita** [comment]
installing command has been updated, if still facing issue, try to downalod it from "https://microg.org/download.html"
